#!/usr/bin/env ruby
require "tmpdir"
require "shellwords"

PACKAGE_FILE = 'package.tar.gz'
PUBLISH_BRANCH = 'packaged'

def main
  Dir.mktmpdir do |tmp|
    # Move site that we just built into temp folder
    run "berks package #{PACKAGE_FILE}"
    run "mv #{PACKAGE_FILE} #{tmp}"
    run "tar -xzf #{tmp}/#{PACKAGE_FILE} -C #{tmp}"
    # Swith to PUBLISH_BRANCH branch.
    if run "git show-ref --verify --quiet refs/heads/#{PUBLISH_BRANCH}"
      run "git checkout #{PUBLISH_BRANCH}"            # checkout existing branch
    else
      run "git checkout --orphan #{PUBLISH_BRANCH}"   # create new branch with no history
    end
    next if $?.exitstatus != 0      # abort if checkout failed
    # Delete everything (entire contents of the project folder include source code)
    # This gives us a clean folder for the PUBLISH_BRANCH branch
    run "rm -r *"
    # Move the site we just build into root of project folder
    run "mv #{tmp}/cookbooks/* ."
    # Get .gitignore from original repo so we ignore things like .kitchen/
    system "git checkout master -- .gitignore"
    # Commit site changes to PUBLISH_BRANCH branch and push to Github
    message = "Cookbooks updated at #{Time.now.utc}"
    run "git add --all ."
    run "git commit -am #{message.shellescape}"
    run "git push origin #{PUBLISH_BRANCH} --force"
    # Switch back to master branch
    run "git checkout master"
    # Clean stray / ignored files left behind from the package
    run "git clean -xdf"
    puts "Cookbooks published successfully."
  end
end

def run(command)
  puts "--> #{command}"
  system command, exception: true
end

main
